INSERT INTO public.instrument_type ("type") VALUES
	 ('Afoxé'),
	 ('Agogô'),
	 ('Agung'),
	 ('Angklung'),
	 ('Babendil'),
	 ('Bak'),
	 ('Balafon'),
	 ('Batá drum'),
	 ('Cabasa'),
	 ('Cajón');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Carillon'),
	 ('Castanets (Palillos)'),
	 ('Caxirola'),
	 ('Caxixi'),
	 ('Chácaras'),
	 ('Clapstick'),
	 ('Claves'),
	 ('Cowbell'),
	 ('Crotales'),
	 ('Cymbal');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Ferrinho'),
	 ('Flexatone'),
	 ('Octa-Vibraphone'),
	 ('Gandingan'),
	 ('Ghatam'),
	 ('Glockenspiel'),
	 ('Gong'),
	 ('Güiro'),
	 ('Handbells'),
	 ('Handpan');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Hang'),
	 ('Kalimba'),
	 ('Kayamb (Kayamba)'),
	 ('Kemanak'),
	 ('Khartal'),
	 ('Kouxian'),
	 ('Kulintang'),
	 ('Maraca'),
	 ('Marimba'),
	 ('Mbira');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Pate'),
	 ('Qairaq (Kairak)'),
	 ('Shekere'),
	 ('Slit drum'),
	 ('Spoon'),
	 ('Steelpan'),
	 ('Tambourine'),
	 ('Teponaztli'),
	 ('Triangle'),
	 ('Trash Tube');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Txalaparta'),
	 ('Vibraphone'),
	 ('Vibraslap'),
	 ('Washboard'),
	 ('Wood block'),
	 ('Wooden fish'),
	 ('Xylophone'),
	 ('Zill'),
	 ('Sandpaper blocks'),
	 ('Ekwe');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Agida'),
	 ('Alfaia'),
	 ('Apinti'),
	 ('Arobapá'),
	 ('Ashiko'),
	 ('Atabaque'),
	 ('Baboula'),
	 ('Balaban (drum)'),
	 ('Balsié'),
	 ('Bamboula');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Bara'),
	 ('Barrel drum'),
	 ('"Barriles'),
	 ('buleador'),
	 ('primo'),
	 ('repicador'),
	 ('subidor"'),
	 ('Bass drum'),
	 ('Bedug'),
	 ('Bodhrán');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Bongo drums'),
	 ('Boobam'),
	 ('"Candombe'),
	 ('chico'),
	 ('repique'),
	 ('piano"'),
	 ('"Chenda (Chande)'),
	 ('Uruttu chenda'),
	 ('Veekku chenda'),
	 ('Acchan chenda"');
INSERT INTO public.instrument_type ("type") VALUES
	 ('"Conga  (Tumbadora)'),
	 ('ricardo  (smallest)'),
	 ('requinto'),
	 ('quinto'),
	 ('conga'),
	 ('tumba'),
	 ('supertumba (largest)"'),
	 ('Cuíca'),
	 ('Culo''e puya'),
	 ('Cultrun');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Dabakan'),
	 ('Daf (Dap'),
	 ('Damaru'),
	 ('Davul (dhol'),
	 ('Dayereh'),
	 ('Den-den daiko'),
	 ('Dhak'),
	 ('Dhimay (Dhimaya)'),
	 ('Dhol'),
	 ('Dholak (Dholaki)');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Dimdi'),
	 ('Djembe'),
	 ('Dollu'),
	 ('Drum kit'),
	 ('Dunun  (Dundun)'),
	 ('Gran Cassa'),
	 ('Goblet drum'),
	 ('Gong bass drum'),
	 ('Hira-daiko'),
	 ('Idakka');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Ilimba drum'),
	 ('Ingoma'),
	 ('Shakwe'),
	 ('Inyahura'),
	 ('Igihumurizo"'),
	 ('Janggu (Janggo)'),
	 ('Junjung'),
	 ('Kakko'),
	 ('Kanjira'),
	 ('Kebero');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Kendang (Gendang)'),
	 ('Khol (Mrdanga)'),
	 ('Krakebs'),
	 ('Lambeg drum'),
	 ('Madhalam'),
	 ('Madal'),
	 ('Maddale'),
	 ('"Maktoum (maktoom)'),
	 ('Maram'),
	 ('Mirwas');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Mridangam'),
	 ('Nagara (drum)'),
	 ('Naqareh'),
	 ('Ney (flute)'),
	 ('O-daiko'),
	 ('Okedo-daiko'),
	 ('Octaban'),
	 ('Padayani thappu'),
	 ('Pakhavaj'),
	 ('Pandeiro');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Pandero'),
	 ('Parai'),
	 ('Qilaut'),
	 ('Rebana'),
	 ('Sabar'),
	 ('Sambal'),
	 ('Samphor'),
	 ('Shime-daiko'),
	 ('Snare drum'),
	 ('Surdo');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Tabla'),
	 ('Taiko'),
	 ('Talking drum'),
	 ('Tsukeshime-daiko'),
	 ('Tambor huacana'),
	 ('Tambori'),
	 ('Tamborim'),
	 ('Tamborita calentana (Mexico)'),
	 ('Tambou bas a dé fas'),
	 ('Tambou bas a yon fas');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Tan-tan'),
	 ('Taphon'),
	 ('Tar'),
	 ('Tbilat'),
	 ('Thavil'),
	 ('Timbales (Pailas)'),
	 ('Timpani (kettledrum)'),
	 ('Tom-tom drum'),
	 ('Tombak'),
	 ('Tsuzumi');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Tsuri-daiko'),
	 ('unpitched repique'),
	 ('Uchiwa-daiko'),
	 ('Celesta'),
	 ('Crystallophone'),
	 ('Glasschord'),
	 ('Glass harmonica'),
	 ('Hydraulophone'),
	 ('Plasmaphone'),
	 ('Pyrophone');
INSERT INTO public.instrument_type ("type") VALUES
	 ('Quintephone'),
	 ('"Asadullah (Meerut'),
	 ('Shishi odoshi (Japan)'),
	 ('Suikinkutsu (Japanese water zither)'),
	 ('Wobble board (Australia)');
