INSERT INTO public.rentable_instrument (brand,model,price,instrument_type_id) VALUES
	 ('Ullamcorper Duis PC','est mauris,',263,144),
	 ('Amet Ante LLC','convallis erat,',323,30),
	 ('Arcu Sed Foundation','vitae, posuere',256,87),
	 ('Vivamus Nisi Inc.','Nunc lectus',387,113),
	 ('Sodales Associates','egestas. Aliquam',484,8),
	 ('Eu Augue Institute','luctus ut,',394,67),
	 ('Nonummy Ultricies Associates','tincidunt nibh.',404,181),
	 ('Sed Auctor LLP','consectetuer adipiscing',325,112),
	 ('Velit Corporation','Fusce mi',219,60),
	 ('Non Corporation','odio a',399,39);
INSERT INTO public.rentable_instrument (brand,model,price,instrument_type_id) VALUES
	 ('Ac LLP','ac turpis',161,107),
	 ('Nisl Nulla Corp.','iaculis nec,',253,60),
	 ('Et Magnis Dis Corp.','at risus.',418,22),
	 ('Diam At Corporation','Donec tempor,',438,117),
	 ('Egestas Sed LLC','sed sem',385,11),
	 ('Mollis Integer LLC','vitae purus',324,186),
	 ('Ipsum Porta Company','lectus, a',354,104),
	 ('Nascetur Ridiculus Mus Inc.','Donec tincidunt.',465,98),
	 ('Pede LLP','amet luctus',261,47),
	 ('Vestibulum Nec LLP','fringilla euismod',173,110);
INSERT INTO public.rentable_instrument (brand,model,price,instrument_type_id) VALUES
	 ('Aliquet Vel Corp.','felis, adipiscing',318,90),
	 ('Nascetur Ridiculus LLC','non enim',322,125),
	 ('Dapibus Rutrum Justo Inc.','amet risus.',456,138),
	 ('Leo Vivamus Nibh LLP','lectus. Nullam',222,92),
	 ('Libero Proin Foundation','orci. Ut',285,132),
	 ('Consectetuer Adipiscing PC','augue ut',441,164),
	 ('Eu Tellus Phasellus Ltd','in consequat',267,90),
	 ('Ullamcorper Velit Company','pede. Suspendisse',412,82),
	 ('Et Magnis Corporation','Proin nisl',374,165),
	 ('Cras PC','et malesuada',461,178);
INSERT INTO public.rentable_instrument (brand,model,price,instrument_type_id) VALUES
	 ('Diam Corporation','ligula tortor,',497,49),
	 ('Per Inceptos Hymenaeos PC','lectus convallis',236,76),
	 ('Non Foundation','Aenean eget',319,64),
	 ('Nibh Aliquam Consulting','erat. Vivamus',371,24),
	 ('Tristique Pharetra Corp.','leo. Vivamus',228,191),
	 ('Magna Et Consulting','malesuada ut,',198,26),
	 ('Sapien Nunc Ltd','luctus et',497,187),
	 ('Sem Vitae Aliquam Corporation','fermentum arcu.',368,162),
	 ('Enim Mi Tempor Inc.','primis in',325,95),
	 ('Mauris Non LLC','auctor non,',286,71);
INSERT INTO public.rentable_instrument (brand,model,price,instrument_type_id) VALUES
	 ('Imperdiet Nec Company','fringilla mi',225,53),
	 ('Eget Massa Suspendisse Associates','sit amet',411,189),
	 ('Consectetuer Inc.','eget, volutpat',427,67),
	 ('Ipsum Cursus Institute','erat. Etiam',476,37),
	 ('Adipiscing Lacus Ut PC','ipsum primis',254,92),
	 ('A Neque Inc.','augue ac',252,177),
	 ('Urna Company','tortor. Integer',432,122),
	 ('Malesuada Institute','facilisi. Sed',392,145),
	 ('Quis Massa Consulting','commodo ipsum.',315,66),
	 ('Nibh Dolor Limited','In ornare',326,180);
